# Generated by Django 5.1 on 2025-02-26 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0003_remove_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='barangay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_address',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
