# Generated by Django 5.1 on 2025-02-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0006_alter_attendance_date_alter_attendance_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admin_id_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_system.admin'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], max_length=2, null=True),
        ),
    ]
