# Generated by Django 5.1 on 2025-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0008_employee_payroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_status',
            field=models.CharField(blank=True, choices=[('PEND', 'Pending'), ('PROC', 'Processed')], max_length=4, null=True),
        ),
    ]
