# Generated by Django 5.1 on 2025-02-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0009_alter_employee_payroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(choices=[('Grade School', 'Grade School'), ('High School', 'High School'), ("Bachelor's Degree", "Bachelor's Degree"), ('Vocational Education', 'Vocational Education'), ("Master's Degree", "Master's Degree")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payroll_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], max_length=9, null=True),
        ),
    ]
