# Generated by Django 5.1 on 2025-03-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0011_remove_employee_admin_id_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='payroll_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], default='PENDING', max_length=9, null=True),
        ),
    ]
