# Generated by Django 5.1 on 2025-03-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0013_alter_payroll_employee_id_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='attendance_id_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_system.attendance'),
        ),
    ]
