# Generated by Django 5.1 on 2025-03-05 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0014_alter_payroll_attendance_id_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='payroll_system.employee'),
        ),
    ]
