# Generated by Django 5.1 on 2025-03-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0015_attendance_active_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rate',
        ),
        migrations.AddField(
            model_name='payroll',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
