# Generated by Django 5.1.7 on 2025-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0018_attendance_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=8),
        ),
    ]
