# Generated by Django 5.1.7 on 2025-03-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0019_alter_attendance_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='active_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
    ]
