# Generated by Django 5.1 on 2025-03-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0020_remove_attendance_active_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='admin_id_fk',
        ),
    ]
