# Generated by Django 5.1 on 2025-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0021_remove_history_admin_id_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
