# Generated by Django 5.1.7 on 2025-05-03 08:46

import django.db.models.deletion
import django.utils.timezone
import payroll_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brgyDesc', models.CharField(max_length=255)),
                ('regCode', models.CharField(max_length=10)),
                ('provCode', models.CharField(max_length=10)),
                ('citymunCode', models.CharField(max_length=10)),
                ('brgyCode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'refbrgy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=10)),
                ('citymunDesc', models.CharField(max_length=255)),
                ('regDesc', models.CharField(max_length=10)),
                ('provCode', models.CharField(max_length=10)),
                ('citymunCode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'refcitymun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=10)),
                ('provDesc', models.CharField(max_length=255)),
                ('regCode', models.CharField(max_length=10)),
                ('provCode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'refprovince',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=10)),
                ('regDesc', models.CharField(max_length=255)),
                ('regCode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'refregion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='images/', validators=[payroll_system.models.validate_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.barangay')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.city')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.province')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.region')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('date_of_birth', models.DateField(null=True)),
                ('contact_number', models.CharField(max_length=15, null=True)),
                ('emergency_contact', models.CharField(max_length=15, null=True)),
                ('highest_education', models.CharField(choices=[('Grade School', 'Grade School'), ('High School', 'High School'), ("Bachelor's Degree", "Bachelor's Degree"), ('Vocational Education', 'Vocational Education'), ("Master's Degree", "Master's Degree")], max_length=20, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=2083, null=True)),
                ('rate', models.FloatField(default=0)),
                ('date_of_employment', models.DateField(default=django.utils.timezone.now)),
                ('employee_status', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=9, null=True)),
                ('active_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('absences', models.IntegerField(default=0)),
                ('employee_image', models.ImageField(upload_to='images/', validators=[payroll_system.models.validate_image_size])),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.barangay')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.city')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.province')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_system.region')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours_worked', models.FloatField(default=0)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='payroll_system.employee')),
            ],
            options={
                'ordering': ['date', 'time_in'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('payroll_period_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('payroll_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], default='PENDING', max_length=9)),
                ('type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BY-WEEKLY', 'By-weekly'), ('MONTHLY', 'Monthly')], max_length=9)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrollperiods', to='payroll_system.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('payroll_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_worked', models.IntegerField(default=0)),
                ('gross_pay', models.FloatField(default=0)),
                ('incentives', models.FloatField(default=0)),
                ('deductions', models.FloatField(default=0)),
                ('cash_advance', models.FloatField(default=0)),
                ('net_pay', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrollrecords', to='payroll_system.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrollrecords', to='payroll_system.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='payroll_system.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='payroll_system.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='payroll_system.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='payroll_system.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='payroll_system.vehicle')),
            ],
        ),
    ]
