# Generated by Django 5.1 on 2025-02-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
    ]
