# Generated by Django 5.1.7 on 2025-04-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='municipality',
            new_name='city',
        ),
    ]
