# Generated by Django 5.1.7 on 2025-05-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrecord',
            name='deductions',
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('deduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('PAGIBIG', 'Pag-IBIG')], max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll_system.payrollrecord')),
            ],
        ),
    ]
