# Generated by Django 5.1 on 2025-02-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0002_alter_employee_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
