# Generated by Django 5.1.7 on 2025-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0002_remove_payrollrecord_deductions_deduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='rate',
            new_name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='active_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
