# Generated by Django 5.1.7 on 2025-04-27 13:13

import payroll_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0002_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(upload_to='images/', validators=[payroll_system.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(upload_to='images/', validators=[payroll_system.models.validate_image_size]),
        ),
    ]
