# Generated by Django 5.1.7 on 2025-04-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0002_alter_barangay_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barangay',
            table='refbrgy',
        ),
        migrations.AlterModelTable(
            name='city',
            table='refcitymun',
        ),
        migrations.AlterModelTable(
            name='province',
            table='refprovince',
        ),
        migrations.AlterModelTable(
            name='region',
            table='refregion',
        ),
    ]
