# Generated by Django 5.1.7 on 2025-05-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0003_rename_rate_employee_daily_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='employee',
        ),
    ]
