# Generated by Django 5.1.7 on 2025-04-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0003_remove_customer_gender_alter_employee_employee_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='under_time',
        ),
    ]
