# Generated by Django 5.1 on 2025-02-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0004_remove_employee_middle_name_employee_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(choices=[('Elem', 'Elementary'), ('HS', 'High School'), ('Coll', 'College')], max_length=4),
        ),
    ]
