# Generated by Django 5.1.7 on 2025-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0004_remove_payroll_under_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_payday', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='payroll',
            name='cash_advance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
