# Generated by Django 5.1.7 on 2025-05-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0004_remove_payrollperiod_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='payroll_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('INPROGRESS', 'In-Progress')], default='PENDING', max_length=11),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='payroll_system.employee'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payroll_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='payroll_system.payrollperiod'),
        ),
    ]
