# Generated by Django 5.1 on 2025-02-26 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0005_alter_admin_admin_id_alter_employee_employee_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(choices=[('GS', 'Grade School'), ('HS', 'High School'), ('B.', "Bachelor's Degree"), ('Voc. Ed.', 'Vocational Education'), ('M.', "Master's Degree")], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
