# Generated by Django 5.1.6 on 2025-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0005_alter_payrollperiod_payroll_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='deduction_type',
            field=models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('PAGIBIG', 'Pag-Ibig')], max_length=20),
        ),
    ]
