# Generated by Django 5.1.7 on 2025-05-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0006_alter_deduction_deduction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='deduction_type',
            field=models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('PAGIBIG', 'Pag-Ibig'), ('OTHERS', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BY-WEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=9),
        ),
    ]
