# Generated by Django 5.1.7 on 2025-05-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0007_alter_deduction_deduction_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deduction',
            unique_together={('payroll_record', 'deduction_type')},
        ),
    ]
