# Generated by Django 5.1 on 2025-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0007_alter_employee_admin_id_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payroll_status',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time')], max_length=4, null=True),
        ),
    ]
