# Generated by Django 5.1.6 on 2025-05-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0009_cleanup_duplicate_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
