# Generated by Django 5.1 on 2025-02-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0010_alter_employee_employee_status_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='admin_id_fk',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='admin_id_fk',
        ),
    ]
