# Generated by Django 5.1 on 2025-03-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0012_remove_employee_payroll_status_employee_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employee_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll_system.employee'),
        ),
    ]
