# Generated by Django 5.1.7 on 2025-03-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0022_employee_middle_name'),
        ('ph_geography', '0002_alter_barangay_id_alter_barangay_is_urban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='postal_address',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ph_geography.barangay'),
        ),
    ]
