# Generated by Django 5.1.7 on 2025-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0024_barangay_municipality_province_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='barangay',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='province',
        ),
        migrations.AlterField(
            model_name='employee',
            name='municipality',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='province',
            name='region',
        ),
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_experience',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.DeleteModel(
            name='Barangay',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
