# Generated by Django 5.1.7 on 2025-04-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0025_alter_employee_barangay_remove_municipality_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('contact_number', models.CharField(max_length=15, null=True)),
                ('region', models.CharField(default='', max_length=255)),
                ('province', models.CharField(default='', max_length=255)),
                ('municipality', models.CharField(default='', max_length=255)),
                ('barangay', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=100)),
            ],
        ),
    ]
