# Generated by Django 5.1.7 on 2025-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_system', '0016_remove_employee_rate_payroll_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
    ]
